name: ENIGMA_DTI_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.8
  - regex=2021.4.4
  - requests=2.25.1
  - scikit-learn=0.24.1
  - scipy=1.6.2
  - seaborn=0.11.1
  - xlrd=2.0.1
  - xlsxwriter=1.3.8
  - yaml=0.2.5
  - matplotlib=3.7.2
  - pandas=1.4.4
  - openpyxl=3.0.7
  - numpy
  - pip=23.0.1
  - pip:
    - nibabel==5.2.1